blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Sahilll94/Travel-Book/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: Security Issues
    url: mailto:sahilk64555@gmail.com
    about: Report security vulnerabilities privately
